name: Run Snyk Open Source and Code on push to repo
on: push
jobs:
  # Run snyk test on application files
  security:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for open source vulnerabilities & license issues
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: |
             --sarif-file-output=snyk.sarif
             --severity-threshold=high
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
            sarif_file: snyk.sarif
      - name: Run Snyk Code Test for SCA
        uses: snyk/actions/node@master
        continue-on-error: true # DEMO: don't break the build for the demo
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
          command: code test